@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes EditCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([The selected student does not exist])
    :Show error message;
else ([else])
    if () then ([Duplication of phone, email or student id])
    :Show error message;
    else ([else]))
    :Update the information of selected student;
    endif
endif
stop
@enduml
