@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes SelectClassCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([The selected class does not exist in the current ClassBook])
    :Show error message;
else ([else])
    :Display the list of students from the selected class;
endif
stop
@enduml
