@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes AddAttendanceRecordCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([The adding attendance date exists in the current attendance record])
    :Show error message;
else ([else])
    :Add new attendance record for all students;
endif
stop
@enduml
