@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes CreateClassCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([The new class exists in the ClassBook])
    :Show error message;
else ([else])
    :Create new class;
endif
stop
@enduml
